name: test-install-parts

on: [push, pull_request]

jobs:
  arduino-install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: |
        mkdir -p /etc/udev/rules.d/ # just for testing, folder should just exist on the real image
        sudo useradd -m -s /bin/bash mirte 
        MIRTE_SRC_DIR=/usr/local/src/mirte
        ls -ld /usr/local/
        ls -ld /usr/local/src/
        sudo mkdir -p $MIRTE_SRC_DIR
        sudo mkdir $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo cp -r ./* $MIRTE_SRC_DIR/mirte-install-scripts/
        cd $MIRTE_SRC_DIR
        sudo apt update
        sudo git clone https://github.com/mirte-robot/telemetrix4arduino.git mirte-telemetrix4arduino -b develop
        sudo git clone https://github.com/mirte-robot/telemetrix4rpipico.git mirte-telemetrix4rpipico -b develop --recursive
        cd $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo ./install_arduino.sh

  ros2-install:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        type: [mirte, mirte-master]
    steps:
    - uses: actions/checkout@v4
    - shell: /bin/bash
      run: |
        echo $0
        sudo useradd -m -s /bin/bash mirte 
        MIRTE_SRC_DIR=/usr/local/src/mirte
        sudo mkdir -p $MIRTE_SRC_DIR

        sudo mkdir $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo cp -r ./* $MIRTE_SRC_DIR/mirte-install-scripts/
        cd $MIRTE_SRC_DIR
        sudo git clone https://github.com/arendjan/mirte-ros-packages.git mirte-ros-packages -b develop --recursive

        sudo apt update
        cd $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo sed -i '/systemctl/d' install_ROS2.sh # remove systemctl command as it is not available in the github runner/container
        sudo apt install libunwind-dev -y
        MIRTE_TYPE=${{ matrix.type }}
        sudo source ./install_ROS2.sh